### ISSUE TITLE
Feature Request: Combination of Text + Images in Popup

### ISSUE THREAD

**Issue by 4pr3x** [h5p/h5p-image-hotspots#7]
I would like to be able to combine Images and Text in a Popup. Would that be possible to integrate?

**Comment by fnoks** [comment]
That should already be possible to do. Are you using the latest version of this content type?

**Comment by 4pr3x** [comment]
@fnoks Thanks for the quick replay. It seems that our CMS is using an outdated version 1.2.3. I´m now waiting that the update will be made. Will there be a new Point the in the <select> with Text + Image or how was it implemented?

**Comment by fnoks** [comment]
You may add Text, Image and Video (which will be placed below each other) in the order of your choice. You could check it out on h5p.org while waiting for the upgrade :)
