### ISSUE TITLE
Change Color of a Hotspot that was already clicked

### ISSUE THREAD

**Issue by y0x** [h5p/h5p-image-hotspots#9]
Hey,

I have created a feature to enable the user to set a different color for hotspots that were already clicked. 
Screenshots of it are attached. 

I would really like to share this with you, because I think it could also be useful for other ppl and also want to give something back to this awesome community. 

If you like it I´d create a PR. If you would like to have something changed I´d invest the time to make it fit to your requirements. 

Please let me know if you would like to integrate this feature.

![clicked1](https://cloud.githubusercontent.com/assets/23525460/20423126/dadc9806-ad6e-11e6-9229-48d0cbcd1068.png)
![clicked2](https://cloud.githubusercontent.com/assets/23525460/20423127/dae26920-ad6e-11e6-8e74-51778d416f44.png)

**Comment by timothyylim** [comment]
This is a great improvement and I am sure that the rest of the H5P community would like to see it added. If you could make a PR that would be excellent.

**Comment by falcon-git** [comment]
See comments from fnoks on the pull request

**Comment by gemguardian** [comment]
Just wondering if this is a change that we can still welcome in Hotspot. I think it is a good idea that hotspots change color when clicked.

**Comment by y0x** [comment]
@gembuardian sorry I have closed the PR unresolved. I moved to another project and had no time left to make this fit. Feel free to copy the code and make it fit in here.
